added tests to validate tokens objects
infinity-swap/token-lists pull request #36
Opened 2023-02-22 16:11 UTC by Leleking

Validate Mainnet and Testnet Tokens object keys

2023-02-24 21:47 UTC, alexshelkov requested changes

2023-02-24 21:47 UTC, alexshelkov commented on src/__tests__/index.test.ts
> +    console.log(list.tokens[0].toJSON());
Lets remove logs pls

2023-02-24 21:47 UTC, alexshelkov commented on src/utils.ts
> +  if (MainnetTokenList.tokens.length) {
I think this function should be removed and instead we can use jest expect to test if objects are equal. There is a lot of option to compare objects in jest itself, so this function feels not needed.

2023-03-09 11:20 UTC, alexshelkov approved these changes

2023-03-14 12:51 UTC, EstherOA approved these changes

2023-03-14 13:56 UTC, merged